apiVersion: v1
kind: Service
metadata:
  name: r3f-game-service
  labels:
    app: r3f-game
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30000
      protocol: TCP
      name: http
  selector:
    app: r3f-game
---
# LoadBalancer Service für Cloud-Deployments
apiVersion: v1
kind: Service
metadata:
  name: r3f-game-loadbalancer
  labels:
    app: r3f-game
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
    - port: 443
      targetPort: 3000
      protocol: TCP
      name: https
  selector:
    app: r3f-game
